# Generated by Django 6.0 on 2026-06-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0054_bookmarkbundle_filter_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='favicon_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='preview_image_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='web_archive_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
